services:
  db:
    image: postgres:16
    container_name: complex_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - data5434:/var/lib/postgresql/data

volumes:
  data5434:
